@baseUrl = http://localhost:3333

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Nicolas Gomes 1",
  "email": "nicolasgomes1@example.com",
  "password": "123456"
}
